<?php
      session_start();

     
//Verificação da realiazação da autenticação
$usuario_autenticado = false;

//usuários do sistema
$usuarios_compra_certa = array(
    array('email' =>'adm@teste.com.br', 'senha' => '1234'),
    array('email' =>'user@teste.com.br', 'senha' => 'abcd'),
    
);

foreach ($usuarios_compra_certa as $user) { 

    if($user['email'] == $_POST['email'] && $user['senha'] == $_POST['senha'] ){
        $usuario_autenticado = true;
        
    }    
}

if($usuario_autenticado){
    echo'Usuario autenticado';
    $_SESSION['autenticado'] = 'SIM';
}else {
    $_SESSION['autenticado'] = 'NAO';
    header('Location: login.php?login=erro');
}

/*
print_r($_GET);

echo '<br />';

echo $_GET['nome'];
echo '<br />';
echo $_GET['email'];
echo '<br />';
echo $_GET['senha'];
*/


?>
